@startuml

state 新上传 #white
新上传 : 文件上传后可以正常访问
state 过期 #white
过期: 如果设置了有效期, 有效期后将不可访问
state 逻辑删除 #white
逻辑删除: 逻辑上标记为删除, 数据库中仍然存在

[*] --> 新上传: 新建短链接

新上传 -> 过期
过期 --> 逻辑删除
新上传 --> 逻辑删除

逻辑删除 --> [*]: 物理删除

@enduml
