@startuml

state 启用 #white
启用 : 短链接启用后可以正常访问
state 未启用 #white
未启用: 访问后将不再跳转
state 逻辑删除 #white
逻辑删除: 逻辑上标记为删除, 数据库中仍然存在

[*] --> 启用: 新建短链接

启用 -> 未启用
未启用 -> 启用
逻辑删除 --> 启用
启用 --> 逻辑删除
未启用 --> 逻辑删除

逻辑删除 --> [*]: 物理删除

@enduml
