@startuml
skinparam sequence {
LifeLineBackgroundColor #white

ParticipantBorderColor #black
ParticipantBackgroundColor #white
ParticipantFontColor #black

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}

participant User

User -> LinkController: 生成短链接
activate LinkController

LinkController -> LinkService: 创建短链接
activate LinkService

LinkService -> LinkService: 生成短链接
LinkService -> DB: 存储短链接
activate DB
DB --> LinkService: 返回短链接
deactivate DB

LinkService --> LinkController: 返回短链接
deactivate LinkService

LinkController -> User: 返回短链接

deactivate LinkController

@enduml
