@startuml

state 未接单 #white
未接单 : 用户新建的工单
state 接单 #white
接单: 家政人员接单
state 待审批 #white
待审批: 家政人员完成任务后, 等待用户审批
state 工单完成 #white
工单完成: 家政工单完成

[*] --> 未接单: 新建预约工单

未接单 --> 接单: 家政人员接单
接单 --> 待审批: 家政人员完成任务
待审批 -> 工单完成: 用户审批通过

工单完成 -> [*]: 系统自动清理

@enduml
