@startuml

state 待审核 #white
待审核 : 用户新建的申请退款单
state 商家同意退款 #white
state 商家拒绝退款 #white
state 管理员待审核 #white
state 管理员同意退款 #white
state 管理员拒绝退款 #white

[*] -> 待审核: 新建申请退款单
待审核 --> 商家同意退款: 商家同意
待审核 --> 商家拒绝退款: 商家拒绝
商家拒绝退款 --> 管理员待审核: 用户申请管理员介入
管理员待审核 --> 管理员同意退款: 管理员同意
管理员待审核 --> 管理员拒绝退款: 管理员拒绝
商家拒绝退款 --> [*]
管理员拒绝退款 --> [*]

@enduml
