@startmindmap
'最近一次更新时间: 2024-05-05
* 中台系统
** 认证授权
*** 登录认证
*** 注册
*** 退出登录
** 对象存储
*** 小文件存储
*** 大文件分块传输
*** 访问文件
** 短链
*** 短链生成
*** 短链访问
*** 统计访问数据
** 消息下发
*** 短信下发
*** 邮件下发
** 及时通信
*** 单聊
*** 群聊
@endmindmap
