@startuml
'最近一次更新时间: 2024-05-05
left to right direction

:用户: as User

(发送消息) as (Use1)
  (发送短信) as (Use11)
  (发送邮件) as (Use12)

User -down-> (Use1)

(Use1) --> (Use11):extend
(Use1) --> (Use12):extend

@enduml