server:
  servlet:
    context-path: /im
  port: 63088

spring:
  application:
    name: im-server
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.101.65:3306/biz_link?serverTimezone=UTC&userUnicode=true&useSSL=false&
#    username: root
#    password: mysql
  #  data:
  #    redis:
  #      host: 127.0.0.1
  #      port: 6379
  #      password: 123456
  #  mvc:
  #    view:
  #      prefix: /templates/
  #      suffix: .html
  cloud:
    nacos:
      server-addr: 192.168.101.65:8848
      discovery:
        namespace: dev
        group: biz-center